# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'horo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 420)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 271, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 491, 331))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(420, 370, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 370, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Most compatible sign: Sagitarrius"))
        self.label_2.setText(_translate("Form", "You may find yourself feeling particularly bold and confident today, Aries. Your natural leadership skills will be in full force, and you\'ll have the energy and drive to take on any challenge that comes your way. This is a great time to start new projects, take risks, and pursue your goals with passion and enthusiasm.\n"
"\n"
"However, be mindful of your tendency to be impulsive and act before thinking things through. Take a moment to consider the consequences of your actions before making any big moves. This will help you avoid any unnecessary mistakes or setbacks.\n"
"\n"
"In matters of the heart, you may be feeling especially passionate and romantic. This is a great time to express your feelings to that special someone and let them know how much they mean to you. But make sure to communicate clearly and listen to their needs as well.\n"
"\n"
"Overall, this is a powerful and exciting time for you, Aries. Embrace the opportunities that come your way and trust in your instincts to guide you towards success."))
        self.pushButton.setText(_translate("Form", "Finish"))
        self.pushButton_2.setText(_translate("Form", "Share"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
