# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zodiac(object):
    def setupUi(self, Zodiac):
        Zodiac.setObjectName("Zodiac")
        Zodiac.resize(541, 526)
        self.centralwidget = QtWidgets.QWidget(Zodiac)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 211, 51))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 311, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(200, 20, 161, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 110, 521, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 480, 93, 28))
        self.pushButton.setObjectName("pushButton")
        Zodiac.setCentralWidget(self.centralwidget)

        self.retranslateUi(Zodiac)
        QtCore.QMetaObject.connectSlotsByName(Zodiac)

    def retranslateUi(self, Zodiac):
        _translate = QtCore.QCoreApplication.translate
        Zodiac.setWindowTitle(_translate("Zodiac", "MainWindow"))
        self.label.setText(_translate("Zodiac", "Select your Birth Date"))
        self.label_2.setText(_translate("Zodiac", "You are a...{zodiac}"))
        self.textBrowser.setHtml(_translate("Zodiac", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/z_img/aquarius.png\" /></p></body></html>"))
        self.pushButton.setText(_translate("Zodiac", "Continue"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Zodiac = QtWidgets.QMainWindow()
    ui = Ui_Zodiac()
    ui.setupUi(Zodiac)
    Zodiac.show()
    sys.exit(app.exec_())
