# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SWOT(object):
    def setupUi(self, SWOT):
        SWOT.setObjectName("SWOT")
        SWOT.resize(610, 552)
        self.label = QtWidgets.QLabel(SWOT)
        self.label.setGeometry(QtCore.QRect(30, 30, 271, 211))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SWOT)
        self.label_2.setGeometry(QtCore.QRect(320, 30, 271, 211))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SWOT)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 271, 251))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(SWOT)
        self.label_4.setGeometry(QtCore.QRect(320, 270, 271, 211))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(SWOT)
        self.pushButton.setGeometry(QtCore.QRect(490, 510, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SWOT)
        QtCore.QMetaObject.connectSlotsByName(SWOT)

    def retranslateUi(self, SWOT):
        _translate = QtCore.QCoreApplication.translate
        SWOT.setWindowTitle(_translate("SWOT", "Form"))
        self.label.setText(_translate("SWOT", "Strengths:\n"
"\n"
"- Aries is known for their strong willpower and determination.\n"
"- They are natural leaders who are confident and assertive.\n"
"- Aries are energetic and enthusiastic, which makes them great at initiating new projects.\n"
"- They are not afraid of taking risks and are always up for a challenge.\n"
"- Aries are passionate and driven, which makes them great at pursuing their goals."))
        self.label_2.setText(_translate("SWOT", "Weaknesses:\n"
"\n"
"- Aries can be impulsive and quick-tempered, which can lead to rash decisions.\n"
"- They can be selfish and overly competitive, which can strain their relationships with others.\n"
"- Aries can struggle with patience and tend to want immediate results.\n"
"- They may have a tendency to overlook details in their haste to get things done.\n"
"- Aries can become easily bored with routine tasks and may struggle with following through on projects."))
        self.label_3.setText(_translate("SWOT", "Opportunities:\n"
"\n"
"- Aries can take advantage of their natural leadership skills to advance their careers and take on leadership positions.\n"
"- They can use their passion and energy to pursue new hobbies and interests.\n"
"- Aries can focus on developing patience and attention to detail, which can help them succeed in projects that require these skills.\n"
"- They can use their competitive nature to motivate themselves and improve their skills.\n"
"- Aries can explore opportunities for adventure and travel, which aligns with their adventurous nature."))
        self.label_4.setText(_translate("SWOT", "Threats:\n"
"\n"
"- Aries can be prone to burnout due to their high energy levels and tendency to take on too much.\n"
"- They may struggle to work collaboratively with others, which can hinder their progress.\n"
"- Aries may face challenges in situations where they are not in control or are required to follow someone else\'s lead.\n"
"- They can be perceived as aggressive or intimidating, which can negatively impact their relationships with others.\n"
"- Aries may struggle with adapting to change, which can limit their opportunities for growth and development."))
        self.pushButton.setText(_translate("SWOT", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SWOT = QtWidgets.QWidget()
    ui = Ui_SWOT()
    ui.setupUi(SWOT)
    SWOT.show()
    sys.exit(app.exec_())
